package ca.uoguelph.ccs.portal.rest;

import java.io.*;

/**
 * Defines the interface for a content filter.
 *
 * <P>
 *
 * Content filters transform dynamic content generated by a REST
 * portlet into a form suitable for inclusion in the portal page. The
 * filter may perform any transformation, but must not alter the
 * content type of the response, and should try to maintain as much
 * original structure as possible.
 *
 * <P>
 *
 * The primary job of a content filter is to rewrite portlet: URLs and
 * resolve relative URIs, but may perform other functions as well.
 *
 * @author M. Brent Harp
 */
public interface ContentFilter
{
    /**
     * Sets the URI resolver.
     *
     * <P>
     *
     * The filter uses the URI resolver to resolve any URIs it
     * discovers in the portlet response. The resolver must be able to
     * resolve absolute and relative URIs, as well as URIs with the
     * special "portlet:" scheme.
     *
     * @param resolver a URI resolver.
     */
    public void setURIResolver(URIResolver resolver);

    /**
     * Filters a portlet response.
     *
     * @param reader the input reader (from the REST portlet).
     * @param writer the output writer (to the portal container).
     * @throws Exception if an error occurs.
     */
    public void filter (Reader reader, Writer writer)
        throws java.io.IOException;
}
